export const routes = {
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",

  DASHBOARD_INDEX: "dashboard.index",

  USERS_INDEX: "users.index",
  USERS_CREATE: "users.create",
  USERS_STORE: "users.store",
  USERS_EDIT: "users.edit",
  USERS_UPDATE: "users.update",
  USERS_DESTROY: "users.destroy",
  USERS_AJAX_INDEX: "users.ajax.index",

  CUSTOMERS_INDEX: "customers.index",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_STORE: "customers.store",
  CUSTOMERS_EDIT: "customers.edit",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DESTROY: "customers.destroy",
  CUSTOMERS_AJAX_INDEX: "customers.ajax.index",

  VEHICLES_INDEX: "vehicles.index",
  VEHICLES_CREATE: "vehicles.create",
  VEHICLES_STORE: "vehicles.store",
  VEHICLES_EDIT: "vehicles.edit",
  VEHICLES_UPDATE: "vehicles.update",
  VEHICLES_DESTROY: "vehicles.destroy",
  VEHICLES_AJAX_INDEX: "vehicles.ajax.index",

  TANKS_INDEX: "tanks.index",
  TANKS_CREATE: "tanks.create",
  TANKS_STORE: "tanks.store",
  TANKS_EDIT: "tanks.edit",
  TANKS_UPDATE: "tanks.update",
  TANKS_DESTROY: "tanks.destroy",
  TANKS_BARCODE: "tanks.barcode",
  TANKS_AJAX_INDEX: "tanks.ajax.index",
  TANKS_AJAX_PRINT_BARCODES: "tanks.ajax.print-barcodes",

  TANK_CATEGORIES_INDEX: "tank-categories.index",
  TANK_CATEGORIES_CREATE: "tank-categories.create",
  TANK_CATEGORIES_STORE: "tank-categories.store",
  TANK_CATEGORIES_EDIT: "tank-categories.edit",
  TANK_CATEGORIES_UPDATE: "tank-categories.update",
  TANK_CATEGORIES_DESTROY: "tank-categories.destroy",
  TANK_CATEGORIES_AJAX_INDEX: "tank-categories.ajax.index",
  TANK_CATEGORIES_AJAX_SHOW: "tank-categories.ajax.show",

  PRICES_INDEX: "prices.index",
  PRICES_CREATE: "prices.create",
  PRICES_STORE: "prices.store",
  PRICES_EDIT: "prices.edit",
  PRICES_UPDATE: "prices.update",
  PRICES_DESTROY: "prices.destroy",
  PRICES_AJAX_INDEX: "prices.ajax.index",
  PRICES_AJAX_CHECK_UNIQUE: "prices.ajax.check-unique",

  DELIVERIES_INDEX: "deliveries.index",
  DELIVERIES_CREATE: "deliveries.create",
  DELIVERIES_STORE: "deliveries.store",
  DELIVERIES_SHOW: "deliveries.show",
  DELIVERIES_EDIT: "deliveries.edit",
  DELIVERIES_UPDATE: "deliveries.update",
  DELIVERIES_DESTROY: "deliveries.destroy",
  DELIVERIES_AJAX_INDEX: "deliveries.ajax.index",

  CONTRACTS_INDEX: "contracts.index",
  CONTRACTS_CREATE: "contracts.create",
  CONTRACTS_STORE: "contracts.store",
  CONTRACTS_SHOW: "contracts.show",
  CONTRACTS_EDIT: "contracts.edit",
  CONTRACTS_UPDATE: "contracts.update",
  CONTRACTS_DESTROY: "contracts.destroy",
  CONTRACTS_AJAX_INDEX: "contracts.ajax.index",

  FAKTUR_INDEX:"faktur.index",
};
